### ISSUE TITLE
CJK glyphs rendering as "glyph not found" ("tofu") characters

### ISSUE THREAD

**Issue by ssokolow** [flathub/org.freedesktop.Bustle#10]
The Bustle Flatpak appears to not have its fonts configured properly for displaying CJK characters because they render as ["tofu" characters](https://en.wikipedia.org/wiki/Specials_(Unicode_block)). (i.e. Windows-style empty rectangle renderings of the `.notdef` glyph)

For example, try copy-pasting [文字化け](https://en.wikipedia.org/wiki/Mojibake) into the Address field in the Record Address dialog as a minimal-effort test.

I can see this being a big problem for viewing the contents of D-Bus messages on systems not configured for a latin script. (eg. For diagnosing encoding mismatches between two programs, where you need to figure out whether it went wrong on the sending or receiving side.)

If it helps you narrow down the problem, the AntiMicroX, Arduino IDE, Blender, Firefox, FocusWriter, Godot, JDownloader, KCachegrind, Krita, LMMS, MEGAsync, Okteta, Sweet Home 3D, Thunderbird, Tor Browser, and Ungoogled Chromium flatpaks work fine on this issue... though Deluge, Flatseal, HandBrake, Inkscape, and jstest-gtk *do* have the same problem as of my opening this bug. (I've reported bugs for some of them, but not all... since cases like jstest-gtk were a struggle just to *find* a text-entry field to test with.)

**Comment by wjt** [comment]
![Capture d’écran de 2022-01-05 10-57-24](https://user-images.githubusercontent.com/86760/148206781-08cc285a-8b7c-4370-b144-bc7c203d7a31.png)

Works fine on my machine.

Please try running Bustle from a Terminal window. Do you see any suspicious warnings?

```
flatpak run org.freedesktop.Bustle
```

You can also check:

```
flatpak info org.freedesktop.Platform.Locale/x86_64/20.08
```

Which `Subdirectories` are shown as installed?

**Comment by ssokolow** [comment]
> Please try running Bustle from a Terminal window. Do you see any suspicious warnings?

Yes, actually.

```
(bustle:2): Pango-WARNING **: 06:20:58.331: failed to create cairo scaled font, expect ugly output. the offending font is 'VL Gothic 9.9990234375'

(bustle:2): Pango-WARNING **: 06:20:58.332: font_face status is: file not found

(bustle:2): Pango-WARNING **: 06:20:58.332: scaled_font status is: file not found

(bustle:2): Pango-WARNING **: 06:20:58.349: failed to create cairo scaled font, expect ugly output. the offending font is 'VL Gothic 9.9990234375'

(bustle:2): Pango-WARNING **: 06:20:58.349: font_face status is: file not found

(bustle:2): Pango-WARNING **: 06:20:58.349: scaled_font status is: file not found
```

> flatpak info org.freedesktop.Platform.Locale/x86_64/20.08

`Subdirectories: /en`

However, other applications which also report using `org.freedesktop.Platform` version `20.08` like `com.sweethome3d.Sweethome3d` don't exhibit this problem, so I'm guessing it's probably not the Locale support in the platform itself.

Those Pango errors do look promising, though, because I've noticed that all the applications that are exhibiting the problem are GTK-based and all the applications which aren't exhibiting the problem are either not using GTK or are things like Firefox and Ungoogled Chromium which carry along their own implementations of 99% of what GTK provides.

**Comment by ssokolow** [comment]
Aha! `sudo apt-get remove fonts-vlgothic` makes it work!

Could you check whether installing the VL Gothic font breaks it on your system?

**Comment by wjt** [comment]
What is the output of `locale`?

**Comment by ssokolow** [comment]
```
LANG=en_CA.utf8
LANGUAGE=en_CA:en
LC_CTYPE="en_CA.utf8"
LC_NUMERIC="en_CA.utf8"
LC_TIME="en_CA.utf8"
LC_COLLATE="en_CA.utf8"
LC_MONETARY="en_CA.utf8"
LC_MESSAGES="en_CA.utf8"
LC_PAPER="en_CA.utf8"
LC_NAME="en_CA.utf8"
LC_ADDRESS="en_CA.utf8"
LC_TELEPHONE="en_CA.utf8"
LC_MEASUREMENT="en_CA.utf8"
LC_IDENTIFICATION="en_CA.utf8"
LC_ALL=en_CA.utf8
```

**Comment by wjt** [comment]
Simply installing `fonts-vlgothic` had no effect.

Since this affects other apps besides Bustle on your system I'm going to close this ticket. I think https://github.com/flatpak/flatpak/issues/4641 is sufficient to track the issue.

**Comment by ssokolow** [comment]
Yeah. I created that one later, after realizing what was common between the handful of apps which had CJK issues. It makes sense to close this one.
