### ISSUE TITLE
Use the GNOME runtime

### ISSUE THREAD

**Issue by A6GibKm** [flathub/org.freedesktop.Bustle#11]
The freedesktop runtime does not ship Cantarel fonts, and it might look different from machine to machine.

![image](https://user-images.githubusercontent.com/11528996/162730216-cb31227f-ee9b-4c85-acff-3c3a7c845a6d.png)

**Comment by wjt** [comment]
The host's Cantarell (if present) should be available, no? Personally I am not too bothered about this.

**Comment by A6GibKm** [comment]
I am using silverblue and they are not shown. I can certainly see other apps wth the correct font.

**Comment by wjt** [comment]
Anything interesting in the journal?

**Comment by wjt** [comment]
Sure. You may find the commit message in d6b7d7d1882265a13acf9a32ecc0b8f1d93cd961 helpful. How's your Haskell? :D

**Comment by A6GibKm** [comment]
> How's your Haskell

~~Thats a funny way of saying Rust~~ Nonexistent to be honest
